version: '3.8'

services:
  nosyt-automation:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHOP_API_KEY=${WHOP_API_KEY}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - DATABASE_URL=postgresql://nosyt:password@postgres:5432/nosyt_automation
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=nosyt_automation
      - POSTGRES_USER=nosyt
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nosyt-automation
    restart: unless-stopped

volumes:
  postgres_data: